name = "fold-detect-worker"
main = "src/worker.js"
compatibility_date = "2026-04-07"

[triggers]
crons = ["0 */6 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "fold-detect-db"

[vars]
DATASET_URL = "https://raw.githubusercontent.com/KHwang9883/MobileModels-csv/main/models.csv"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

